coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default: on
    patch:
      default: on
    changes:
      default: off

ignore:
  - "examples"  # No need to cover the examples
  - "tests" # Tests are always covered, so makes no sense to include them
  - "src/serialization.rs" # tarpaulin cannot compile serde_derive currently, meaning we can't test serialization.

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
